### ISSUE TITLE
Assertion `locator_ids.empty() || locator_ids.size() == 1' failed

### ISSUE THREAD

**Issue by carteavcar02** [eProsima/Fast-DDS-statistics-backend#132]
Hey,
first of all thanks for great repos!
I've been compiled galactic from source and run:
 export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;ACKNACK_COUNT_TOPIC;DISCOVERY_TOPIC;PHYSICAL_DATA_TOPIC;PUBLICATION_THROUGHPUT_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;NETWORK_LATENCY_TOPIC" && export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

after I'm launching my system via ros2 launch, I'm starting the monitor, select ROS_DOMAIN_ID and the moniter crush, the log:

fastdds_monitor: /fastdds_monitor-ws/src/fastdds_statistics_backend/src/cpp/subscriber/StatisticsParticipantListener.cpp:146: eprosima::statistics_backend::subscriber::StatisticsParticipantListener::process_endpoint_discovery(T&&)::<lambda(const eprosima::fastrtps::rtps::Locator_t&)> [with T = eprosima::fastrtps::rtps::WriterDiscoveryInfo&]: Assertion `locator_ids.empty() || locator_ids.size() == 1' failed.

**Comment by jparisu** [comment]
So, as I have mentioned, this is an issue that we have already fixed in the PR #130 , that is pending for review. Feel free to test this branch and check if the issue persists.

However, if you could facilitate us further information about this issue, we could rule out other causes. Which ROS2 distro are you using? And if it is not the default, which Fast DDS version?
Keep in mind that ROS2 foxy does not support Statistics (however you would still get discovery information).
Also, are you using some cycloneDDS nodes inside your LAN? This could crush the Fast DDS Monitor because of the way of reporting the locators (this is what the PR fixes).
