### ISSUE TITLE
Build Failed with incompatible Generated Types

### ISSUE THREAD

**Issue by deshpandeyash** [eProsima/Fast-DDS-statistics-backend#216]
I am compiling with from source with Cmake and I get this result when building: 

`In file included from /home/lkn/Fast-DDS/Fast-DDS-statistics-backend/src/cpp/StatisticsBackend.cpp:52:
/home/lkn/Fast-DDS/Fast-DDS-statistics-backend/src/cpp/topic_types/typesPubSubTypes.h:36:2: error: #error Generated types is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.`

Followed by a bunch of Type errors. 
I am unsure how to proceed here as I also cannot find a tutorial on what to do. 

Any help would be great.

**Comment by JesusPoderoso** [comment]
Hi @deshpandeyash , thanks for using Fast DDS.
I would recommend you  to use latest stable versions of Fast DDS and Fast DDS Statistics Backend.
New versions of both of them are going to be released really soon, but if you are using  `master` branch in both of them, make sure that you have the changes introdiced in this PR, because solves those types issues: 
- https://github.com/eProsima/Fast-DDS-statistics-backend/pull/210

In any case, the way to solve those issues is by re-generating the types using [Fast DDS Gen tool](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/usage/usage.html).
`~ cd <folder where types are: src/cpp/topic_types/>`
`~ fastddsgen -replace types.idl`

**Comment by deshpandeyash** [comment]
Thanks a lot. Our setup was set to a 6 month old version of FastDDS and changing it was too risky. Therefore, i pulled from [v.0.11.0](https://github.com/eProsima/Fast-DDS-statistics-backend/tree/0.11.0)  and then it worked. 

Just a heads up that the topic_types directory is missing in the main now. I am new to this and don't know if its needed.

**Comment by JesusPoderoso** [comment]
Hi @deshpandeyash, thanks for your concern. The types have been moved from `src/cpp/topic_types`  to `include/fastdds_statistics_backend/topic_types` to expose them as public API. That was needed for the next release, which would be ready in a couple of days.
